extern "C" {
	void custatevecAbs2SumArray(){}
	void custatevecAbs2SumArrayBatched(){}
	void custatevecAbs2SumOnZBasis(){}
	void custatevecAccessorCreate(){}
	void custatevecAccessorCreateView(){}
	void custatevecAccessorDestroy(){}
	void custatevecAccessorGet(){}
	void custatevecAccessorSet(){}
	void custatevecAccessorSetExtraWorkspace(){}
	void custatevecApplyGeneralizedPermutationMatrix(){}
	void custatevecApplyGeneralizedPermutationMatrixGetWorkspaceSize(){}
	void custatevecApplyMatrix(){}
	void custatevecApplyMatrixBatched(){}
	void custatevecApplyMatrixBatchedGetWorkspaceSize(){}
	void custatevecApplyMatrixGetWorkspaceSize(){}
	void custatevecApplyPauliRotation(){}
	void custatevecBatchMeasure(){}
	void custatevecBatchMeasureWithOffset(){}
	void custatevecCollapseByBitString(){}
	void custatevecCollapseByBitStringBatched(){}
	void custatevecCollapseByBitStringBatchedGetWorkspaceSize(){}
	void custatevecCollapseOnZBasis(){}
	void custatevecCommunicatorCreate(){}
	void custatevecCommunicatorDestroy(){}
	void custatevecComputeExpectation(){}
	void custatevecComputeExpectationBatched(){}
	void custatevecComputeExpectationBatchedGetWorkspaceSize(){}
	void custatevecComputeExpectationGetWorkspaceSize(){}
	void custatevecComputeExpectationsOnPauliBasis(){}
	void custatevecCreate(){}
	void custatevecDestroy(){}
	void custatevecDistIndexBitSwapSchedulerCreate(){}
	void custatevecDistIndexBitSwapSchedulerDestroy(){}
	void custatevecDistIndexBitSwapSchedulerGetParameters(){}
	void custatevecDistIndexBitSwapSchedulerSetIndexBitSwaps(){}
	void custatevecEx_(){}
	void custatevecExAbs2SumArray(){}
	void custatevecExApplyMatrix(){}
	void custatevecExApplyPauliRotation(){}
	void custatevecExCommunicatorCreate(){}
	void custatevecExCommunicatorDestroy(){}
	void custatevecExCommunicatorFinalize(){}
	void custatevecExCommunicatorGetSizeAndRank(){}
	void custatevecExCommunicatorInitialize(){}
	void custatevecExComputeExpectationOnPauliBasis(){}
	void custatevecExConfigureStateVectorMultiDevice(){}
	void custatevecExConfigureStateVectorMultiProcess(){}
	void custatevecExConfigureStateVectorSingleDevice(){}
	void custatevecExConfigureSVUpdater(){}
	void custatevecExDictionaryDestroy(){}
	void custatevecExMeasure(){}
	void custatevecExSample(){}
	void custatevecExStateVectorCreateMultiProcess(){}
	void custatevecExStateVectorCreateSingleProcess(){}
	void custatevecExStateVectorDestroy(){}
	void custatevecExStateVectorGetProperty(){}
	void custatevecExStateVectorGetResourcesFromDeviceSubSV(){}
	void custatevecExStateVectorGetResourcesFromDeviceSubSVView(){}
	void custatevecExStateVectorGetState(){}
	void custatevecExStateVectorPermuteIndexBits(){}
	void custatevecExStateVectorReassignWireOrdering(){}
	void custatevecExStateVectorSetMathMode(){}
	void custatevecExStateVectorSetState(){}
	void custatevecExStateVectorSetZeroState(){}
	void custatevecExStateVectorSynchronize(){}
	void custatevecExSVUpdaterApply(){}
	void custatevecExSVUpdaterClear(){}
	void custatevecExSVUpdaterCreate(){}
	void custatevecExSVUpdaterDestroy(){}
	void custatevecExSVUpdaterEnqueueGeneralChannel(){}
	void custatevecExSVUpdaterEnqueueMatrix(){}
	void custatevecExSVUpdaterEnqueueUnitaryChannel(){}
	void custatevecExSVUpdaterGetMaxNumRequiredRandnums(){}
	void custatevecGetDefaultWorkspaceSize(){}
	void custatevecGetDeviceMemHandler(){}
	void custatevecGetErrorName(){}
	void custatevecGetErrorString(){}
	void custatevecGetMathMode(){}
	void custatevecGetProperty(){}
	void custatevecGetStream(){}
	void custatevecGetVersion(){}
	void custatevecInitializeStateVector(){}
	void custatevecLoggerForceDisable(){}
	void custatevecLoggerOpenFile(){}
	void custatevecLoggerSetCallback(){}
	void custatevecLoggerSetCallbackData(){}
	void custatevecLoggerSetFile(){}
	void custatevecLoggerSetLevel(){}
	void custatevecLoggerSetMask(){}
	void custatevecMeasureBatched(){}
	void custatevecMeasureOnZBasis(){}
	void custatevecMultiDeviceSwapIndexBits(){}
	void custatevecSamplerApplySubSVOffset(){}
	void custatevecSamplerCreate(){}
	void custatevecSamplerDestroy(){}
	void custatevecSamplerGetSquaredNorm(){}
	void custatevecSamplerPreprocess(){}
	void custatevecSamplerSample(){}
	void custatevecSetDeviceMemHandler(){}
	void custatevecSetMathMode(){}
	void custatevecSetStream(){}
	void custatevecSetWorkspace(){}
	void custatevecSubSVMigratorCreate(){}
	void custatevecSubSVMigratorDestroy(){}
	void custatevecSubSVMigratorMigrate(){}
	void custatevecSVSwapWorkerCreate(){}
	void custatevecSVSwapWorkerCreateWithSemaphore(){}
	void custatevecSVSwapWorkerDestroy(){}
	void custatevecSVSwapWorkerExecute(){}
	void custatevecSVSwapWorkerSetExtraWorkspace(){}
	void custatevecSVSwapWorkerSetParameters(){}
	void custatevecSVSwapWorkerSetSubSVsP2P(){}
	void custatevecSVSwapWorkerSetSubSVsP2PWithSemaphores(){}
	void custatevecSVSwapWorkerSetTransferWorkspace(){}
	void custatevecSwapIndexBits(){}
	void custatevecTestMatrixType(){}
	void custatevecTestMatrixTypeGetWorkspaceSize(){}
}
